{% set name = "miniwdl-slurm" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ac1635e0f57c8e600f84074d940050cf261ade0ff619f2ed09d273a438f2fc02

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - miniwdl >=1.7.0
    - python >=3.7

test:
  imports:
    - miniwdl_slurm

about:
  home: https://github.com/miniwdl-ext/miniwdl-slurm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: miniwdl slurm backend using singularity

extra:
  recipe-maintainers:
    - rhpvorderman
    - DavyCats
