{% set name = "miniwdl-slurm" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c412ae0cc0bbde0c0ce46a9ca75e81a9209a066ac7ab507abc5835a2434c7269

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - miniwdl >=1.7.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - miniwdl_slurm

about:
  home: https://github.com/miniwdl-ext/miniwdl-slurm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: miniwdl slurm backend using singularity

extra:
  recipe-maintainers:
    - rhpvorderman
    - DavyCats
